# Generated by Django 5.2.4 on 2025-07-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0003_customer_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
