# Generated by Django 5.2.4 on 2025-07-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0004_receipt_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", "kg"),
                    ("g", "g"),
                    ("ltr", "ltr"),
                    ("ml", "ml"),
                    ("pcs", "pcs"),
                    ("box", "box"),
                    ("meter", "meter"),
                    ("dozen", "dozen"),
                ],
                default="pcs",
                max_length=10,
            ),
        ),
    ]
