# Generated by Django 5.2.4 on 2025-07-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0005_item_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
